//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskSimConsoleClient.RiskSimulators {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArmyComposition", Namespace="http://schemas.datacontract.org/2004/07/RiskSimLib")]
    [System.SerializableAttribute()]
    public partial class ArmyComposition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte AllModifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte HighestModifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte LowestModifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte AllModifier {
            get {
                return this.AllModifierField;
            }
            set {
                if ((this.AllModifierField.Equals(value) != true)) {
                    this.AllModifierField = value;
                    this.RaisePropertyChanged("AllModifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte HighestModifier {
            get {
                return this.HighestModifierField;
            }
            set {
                if ((this.HighestModifierField.Equals(value) != true)) {
                    this.HighestModifierField = value;
                    this.RaisePropertyChanged("HighestModifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte LowestModifier {
            get {
                return this.LowestModifierField;
            }
            set {
                if ((this.LowestModifierField.Equals(value) != true)) {
                    this.LowestModifierField = value;
                    this.RaisePropertyChanged("LowestModifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="RiskSimulators.IRiskSimulator")]
    public interface IRiskSimulator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRiskSimulator/EstimateSuccessChance", ReplyAction="http://Microsoft.ServiceModel.Samples/IRiskSimulator/EstimateSuccessChanceRespons" +
            "e")]
        double EstimateSuccessChance(RiskSimConsoleClient.RiskSimulators.ArmyComposition attackingForce, RiskSimConsoleClient.RiskSimulators.ArmyComposition defendingForce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRiskSimulator/EstimateSuccessChance", ReplyAction="http://Microsoft.ServiceModel.Samples/IRiskSimulator/EstimateSuccessChanceRespons" +
            "e")]
        System.Threading.Tasks.Task<double> EstimateSuccessChanceAsync(RiskSimConsoleClient.RiskSimulators.ArmyComposition attackingForce, RiskSimConsoleClient.RiskSimulators.ArmyComposition defendingForce);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRiskSimulator/GetServiceName", ReplyAction="http://Microsoft.ServiceModel.Samples/IRiskSimulator/GetServiceNameResponse")]
        string GetServiceName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRiskSimulator/GetServiceName", ReplyAction="http://Microsoft.ServiceModel.Samples/IRiskSimulator/GetServiceNameResponse")]
        System.Threading.Tasks.Task<string> GetServiceNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRiskSimulatorChannel : RiskSimConsoleClient.RiskSimulators.IRiskSimulator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RiskSimulatorClient : System.ServiceModel.ClientBase<RiskSimConsoleClient.RiskSimulators.IRiskSimulator>, RiskSimConsoleClient.RiskSimulators.IRiskSimulator {
        
        public RiskSimulatorClient() {
        }
        
        public RiskSimulatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RiskSimulatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RiskSimulatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RiskSimulatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double EstimateSuccessChance(RiskSimConsoleClient.RiskSimulators.ArmyComposition attackingForce, RiskSimConsoleClient.RiskSimulators.ArmyComposition defendingForce) {
            return base.Channel.EstimateSuccessChance(attackingForce, defendingForce);
        }
        
        public System.Threading.Tasks.Task<double> EstimateSuccessChanceAsync(RiskSimConsoleClient.RiskSimulators.ArmyComposition attackingForce, RiskSimConsoleClient.RiskSimulators.ArmyComposition defendingForce) {
            return base.Channel.EstimateSuccessChanceAsync(attackingForce, defendingForce);
        }
        
        public string GetServiceName() {
            return base.Channel.GetServiceName();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceNameAsync() {
            return base.Channel.GetServiceNameAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="RiskSimulators.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")]
        double Add(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")]
        double Subtract(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")]
        double Multiply(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")]
        double Divide(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : RiskSimConsoleClient.RiskSimulators.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<RiskSimConsoleClient.RiskSimulators.ICalculator>, RiskSimConsoleClient.RiskSimulators.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double n1, double n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double n1, double n2) {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public double Subtract(double n1, double n2) {
            return base.Channel.Subtract(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2) {
            return base.Channel.SubtractAsync(n1, n2);
        }
        
        public double Multiply(double n1, double n2) {
            return base.Channel.Multiply(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2) {
            return base.Channel.MultiplyAsync(n1, n2);
        }
        
        public double Divide(double n1, double n2) {
            return base.Channel.Divide(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2) {
            return base.Channel.DivideAsync(n1, n2);
        }
    }
}
