//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRoleInformationRequest", Namespace="http://schemas.datacontract.org/2004/07/IdentityManager.Contract.RoleService")]
    public partial class GetRoleInformationRequest : object
    {
        
        private int RoleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRoleInformationResponse", Namespace="http://schemas.datacontract.org/2004/07/IdentityManager.Contract.RoleService")]
    public partial class GetRoleInformationResponse : object
    {
        
        private ServiceReference1.RoleInformation RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ServiceReference1.RoleInformation Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleInformation", Namespace="http://schemas.datacontract.org/2004/07/IdentityManager.Contract.Common")]
    public partial class RoleInformation : object
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRoleListRequest", Namespace="http://schemas.datacontract.org/2004/07/IdentityManager.Contract.RoleService")]
    public partial class GetRoleListRequest : object
    {
        
        private System.Nullable<int> ContactIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ContactId
        {
            get
            {
                return this.ContactIdField;
            }
            set
            {
                this.ContactIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRoleListResponse", Namespace="http://schemas.datacontract.org/2004/07/IdentityManager.Contract.RoleService")]
    public partial class GetRoleListResponse : object
    {
        
        private ServiceReference1.RoleInformation[] RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RoleInformation[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nphase.com/identitymanager", ConfigurationName="ServiceReference1.IRoleService")]
    public interface IRoleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nphase.com/identitymanager/IRoleService/GetRoleInformation", ReplyAction="http://nphase.com/identitymanager/IRoleService/GetRoleInformationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Output")]
        System.Threading.Tasks.Task<ServiceReference1.GetRoleInformationResponse> GetRoleInformationAsync(ServiceReference1.GetRoleInformationRequest Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nphase.com/identitymanager/IRoleService/GetRoleList", ReplyAction="http://nphase.com/identitymanager/IRoleService/GetRoleListResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Output")]
        System.Threading.Tasks.Task<ServiceReference1.GetRoleListResponse> GetRoleListAsync(ServiceReference1.GetRoleListRequest Input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleServiceChannel : ServiceReference1.IRoleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IRoleService>, ServiceReference1.IRoleService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RoleServiceClient() : 
                base(RoleServiceClient.GetDefaultBinding(), RoleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRoleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), RoleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RoleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetRoleInformationResponse> GetRoleInformationAsync(ServiceReference1.GetRoleInformationRequest Input)
        {
            return base.Channel.GetRoleInformationAsync(Input);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetRoleListResponse> GetRoleListAsync(ServiceReference1.GetRoleListRequest Input)
        {
            return base.Channel.GetRoleListAsync(Input);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRoleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\"Cannot find endpoint with name \'{0}\'.\"", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRoleService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52444/RoleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("\"Cannot find endpoint with name \'{0}\'.\"", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RoleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRoleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RoleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRoleService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRoleService,
        }
    }
}
